### ISSUE TITLE
profiling format specification

### ISSUE THREAD

**Issue by fungs** [CAMI-challenge/contest_information#8]
When I see Peter Hofmann's toy data profiles, there are still some open questions concerning the profiling output format:

1) Does TAXPATH include the TAXID itself? As this would be redundant with the TAXID column, I wouldn't do so.

2) Should TAXPATH have trailing |'s? I believe this is not meaningful.

3) Should we restrict TAXPATHSN/TAXPATH_SN to have the same length or at most the length of TAXPATH+1?

**Comment by asczyrba** [comment]
re 2) I would keep the trailing |'s. This way you always get the same number of elements when you split by '|'

**Comment by fungs** [comment]
By trailing | I meant
tax1|tax2| intead of tax1|tax2

But I agree that we could simply require the number of | to match the rank tag definition for easier parsing. This could be relaxed in later versions while maintaining backward compatability. This would mean that the full path has always to be given and field to be left empty for unresolved taxa.

**Comment by fungs** [comment]
This refers to the current draft on bioboxes/rfc@a7e32d36b2c27c67ab41a0d1b9c9635c190e3652

**Comment by fungs** [comment]
I resolved this trying to reproduce the original example, which means that a trailing | is not allowed and the last entry in the path must correspond to the level taxon it represents. The format allows to pad extra leaf nodes after a full path only when the RANK column field is empty.

bioboxes/rfc@e098dc8dec3243ba31ec986e7855cb449c840c66

We need to check that the files which we provide are in the correct format.
